sudo: required
language: java
jdk:
  - oraclejdk8

before_install:
- echo "MAVEN_OPTS='-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseG1GC -XX:-UseGCOverheadLimit'" > ~/.mavenrc

install: travis_wait 60 mvn -q test -fae

addons:
  apt:
    packages:
    - oracle-java8-installer

cache:
  directories:
  - .autoconf
  - $HOME/.m2
